CREATE TABLE IF NOT EXISTS promotion_campaign (
  id                  BIGINT PRIMARY KEY AUTO_INCREMENT,
  code                VARCHAR(64) NOT NULL,
  section             VARCHAR(40) NOT NULL,
  title               VARCHAR(160) NOT NULL,
  subtitle            VARCHAR(220) NULL,
  description         VARCHAR(600) NULL,
  city                VARCHAR(100) NULL,
  image_url           VARCHAR(500) NULL,
  badge_text          VARCHAR(40) NULL,
  discount_text       VARCHAR(80) NULL,
  currency            VARCHAR(10) NOT NULL DEFAULT 'KRW',
  coupon_value_type   VARCHAR(16) NOT NULL DEFAULT 'PERCENT',
  coupon_value        DECIMAL(10,2) NOT NULL DEFAULT 0,
  min_order_amount    BIGINT NOT NULL DEFAULT 0,
  issue_limit         INT NOT NULL,
  issued_count        INT NOT NULL DEFAULT 0,
  starts_at           DATETIME(3) NOT NULL,
  ends_at             DATETIME(3) NOT NULL,
  priority            INT NOT NULL DEFAULT 0,
  status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_promotion_campaign_code (code),
  KEY idx_promotion_campaign_section (section, status, starts_at, ends_at),
  KEY idx_promotion_campaign_city (city, status, starts_at, ends_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS promotion_coupon_claim (
  id                  BIGINT PRIMARY KEY AUTO_INCREMENT,
  campaign_id         BIGINT NOT NULL,
  user_id             BIGINT NOT NULL,
  coupon_code         VARCHAR(64) NOT NULL,
  status              VARCHAR(20) NOT NULL DEFAULT 'ISSUED',
  claimed_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  expires_at          DATETIME(3) NULL,
  used_at             DATETIME(3) NULL,
  created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_promotion_claim_campaign_user (campaign_id, user_id),
  UNIQUE KEY uk_promotion_claim_coupon_code (coupon_code),
  KEY idx_promotion_claim_user (user_id, claimed_at),
  CONSTRAINT fk_promotion_claim_campaign FOREIGN KEY (campaign_id) REFERENCES promotion_campaign(id),
  CONSTRAINT fk_promotion_claim_user FOREIGN KEY (user_id) REFERENCES user_account(id)
) ENGINE=InnoDB;

INSERT INTO promotion_campaign(
  code, section, title, subtitle, description, city, image_url, badge_text, discount_text,
  currency, coupon_value_type, coupon_value, min_order_amount, issue_limit, issued_count,
  starts_at, ends_at, priority, status
)
VALUES
  (
    'HOME_HOTEL_SALE_MEGA_60',
    'HOTEL_SALE',
    'MEGA SALE 최대 60% 할인',
    '숙소/패키지 예약 쿠폰 선착순 발급',
    '한정 수량 쿠폰으로 주요 도시 숙소를 할인된 가격으로 예약하세요.',
    NULL,
    'https://picsum.photos/seed/stayvista-promo-mega-60/960/520',
    'MEGA SALE',
    '최대 60% 할인',
    'KRW',
    'PERCENT',
    10.00,
    120000,
    1200,
    0,
    DATE_SUB(NOW(3), INTERVAL 1 DAY),
    DATE_ADD(NOW(3), INTERVAL 30 DAY),
    120,
    'ACTIVE'
  ),
  (
    'HOME_HOTEL_SALE_LALIT_15',
    'HOTEL_SALE',
    'The Lalit 제휴 최대 15%',
    '서울/부산 시티 호텔 대상',
    '체크인 7일 전 예약 시 추가 할인 혜택을 제공합니다.',
    'Seoul',
    'https://picsum.photos/seed/stayvista-promo-lalit-15/960/520',
    'PARTNER PICK',
    '최대 15% 할인',
    'KRW',
    'PERCENT',
    7.50,
    90000,
    800,
    0,
    DATE_SUB(NOW(3), INTERVAL 2 DAY),
    DATE_ADD(NOW(3), INTERVAL 21 DAY),
    110,
    'ACTIVE'
  ),
  (
    'HOME_HOTEL_SALE_NINE_TREE_8',
    'HOTEL_SALE',
    'Nine Tree 프로모션',
    '도심형 숙소 얼리버드',
    '기간 내 체크인 예약 건에 대해 자동 할인 쿠폰이 적용됩니다.',
    'Seoul',
    'https://picsum.photos/seed/stayvista-promo-nine-tree/960/520',
    'CITY DEAL',
    '최대 8% 할인',
    'KRW',
    'PERCENT',
    5.00,
    70000,
    1000,
    0,
    DATE_SUB(NOW(3), INTERVAL 1 DAY),
    DATE_ADD(NOW(3), INTERVAL 14 DAY),
    100,
    'ACTIVE'
  ),
  (
    'HOME_ACTIVITY_TICKET_10',
    'ACTIVITY_PROMO',
    '즐길 거리 얼리버드 10%',
    '티켓/패키지 결합 구매 추천',
    '체험형 상품 전용 쿠폰을 선착순으로 발급합니다.',
    NULL,
    'https://picsum.photos/seed/stayvista-activity-promo-10/960/520',
    'ACTIVITY',
    '최대 10% 할인',
    'KRW',
    'PERCENT',
    10.00,
    30000,
    900,
    0,
    DATE_SUB(NOW(3), INTERVAL 1 DAY),
    DATE_ADD(NOW(3), INTERVAL 18 DAY),
    90,
    'ACTIVE'
  ),
  (
    'HOME_ACTIVITY_PACKAGE_5',
    'ACTIVITY_PROMO',
    '패키지 재고 연동 특가',
    '부산/제주 액티비티 집중',
    '지정 기간 내 패키지 구매 시 즉시 할인이 적용됩니다.',
    'Busan',
    'https://picsum.photos/seed/stayvista-activity-promo-05/960/520',
    'LIMITED',
    '최대 5% 할인',
    'KRW',
    'PERCENT',
    5.00,
    40000,
    600,
    0,
    DATE_SUB(NOW(3), INTERVAL 1 DAY),
    DATE_ADD(NOW(3), INTERVAL 12 DAY),
    80,
    'ACTIVE'
  ),
  (
    'HOME_RECOMMENDED_STAY_BRAND_ASTERIA',
    'RECOMMENDED_STAY',
    'Asteria 추천 숙소전',
    '프리미엄 시티뷰 객실 라인업',
    '브랜드 추천 숙소 예약 시 쿠폰을 발급합니다.',
    NULL,
    'https://picsum.photos/seed/stayvista-brand-asteria/960/520',
    'BRAND DEAL',
    '최대 12% 할인',
    'KRW',
    'PERCENT',
    6.00,
    110000,
    500,
    0,
    DATE_SUB(NOW(3), INTERVAL 1 DAY),
    DATE_ADD(NOW(3), INTERVAL 24 DAY),
    70,
    'ACTIVE'
  ),
  (
    'HOME_RECOMMENDED_STAY_HARBORLINE',
    'RECOMMENDED_STAY',
    'Harborline 플래그십',
    '바다 전망 객실 추천',
    '해변 인근 인기 숙소 대상 프로모션입니다.',
    'Busan',
    'https://picsum.photos/seed/stayvista-brand-harborline/960/520',
    'FLAGSHIP',
    '최대 10% 할인',
    'KRW',
    'PERCENT',
    5.50,
    95000,
    450,
    0,
    DATE_SUB(NOW(3), INTERVAL 1 DAY),
    DATE_ADD(NOW(3), INTERVAL 19 DAY),
    65,
    'ACTIVE'
  )
ON DUPLICATE KEY UPDATE
  section = VALUES(section),
  title = VALUES(title),
  subtitle = VALUES(subtitle),
  description = VALUES(description),
  city = VALUES(city),
  image_url = VALUES(image_url),
  badge_text = VALUES(badge_text),
  discount_text = VALUES(discount_text),
  currency = VALUES(currency),
  coupon_value_type = VALUES(coupon_value_type),
  coupon_value = VALUES(coupon_value),
  min_order_amount = VALUES(min_order_amount),
  issue_limit = VALUES(issue_limit),
  issued_count = LEAST(issued_count, VALUES(issue_limit)),
  starts_at = VALUES(starts_at),
  ends_at = VALUES(ends_at),
  priority = VALUES(priority),
  status = VALUES(status),
  updated_at = NOW(3);
