package com.devoceanblue.stayvista.common.api

import org.springframework.http.HttpStatus

enum class ErrorCode(
    val httpStatus: HttpStatus,
    val code: String,
) {
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST, "VALIDATION_ERROR"),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "UNAUTHORIZED"),
    FORBIDDEN(HttpStatus.FORBIDDEN, "FORBIDDEN"),
    NOT_FOUND(HttpStatus.NOT_FOUND, "NOT_FOUND"),
    CONFLICT(HttpStatus.CONFLICT, "CONFLICT"),
    RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS, "RATE_LIMITED"),
    QUEUE_REQUIRED(HttpStatus.TOO_MANY_REQUESTS, "QUEUE_REQUIRED"),
    INTERNAL(HttpStatus.INTERNAL_SERVER_ERROR, "INTERNAL"),
    IDEMPOTENCY_REPLAY_MISMATCH(HttpStatus.CONFLICT, "IDEMPOTENCY_REPLAY_MISMATCH"),
    BOOKING_OVERBOOKED(HttpStatus.CONFLICT, "BOOKING_OVERBOOKED"),
    BOOKING_EXPIRED(HttpStatus.CONFLICT, "BOOKING_EXPIRED"),
    BOOKING_STATE_CONFLICT(HttpStatus.CONFLICT, "BOOKING_STATE_CONFLICT"),
    INVENTORY_TOTAL_BELOW_COMMITTED(HttpStatus.CONFLICT, "INVENTORY_TOTAL_BELOW_COMMITTED"),
    INVENTORY_INVARIANT_VIOLATION(HttpStatus.CONFLICT, "INVENTORY_INVARIANT_VIOLATION"),
    TICKET_SOLD_OUT(HttpStatus.CONFLICT, "TICKET_SOLD_OUT"),
    ORDER_EXPIRED(HttpStatus.CONFLICT, "ORDER_EXPIRED"),
    ORDER_STATE_CONFLICT(HttpStatus.CONFLICT, "ORDER_STATE_CONFLICT"),
    QUEUE_TOKEN_INVALID(HttpStatus.TOO_MANY_REQUESTS, "QUEUE_TOKEN_INVALID"),
    ALREADY_USED(HttpStatus.CONFLICT, "ALREADY_USED"),
    EXPIRED(HttpStatus.CONFLICT, "EXPIRED"),
}
